// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfeukrzeeudeontcvkww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZXVrcnplZXVkZW9udGN2a3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjYwMDEsImV4cCI6MjA2NjIwMjAwMX0.cSag-CToR0vPavcrCOTbFEYMOIZ8Yngg_p5PV7hGRcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);